image:
  repository: ghcr.io/13nour11/config-server
  tag: latest

containerPort: 8888
service:
  port: 8888

env:
  EUREKA_URL: http://eureka-server:8761/eureka/
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.ecommerce:9092
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin.ecommerce:9411/api/v2/spans
