image:
  repository: ghcr.io/13nour11/capstone-platform/config-server
  tag: latest   # CI commits the git sha here on the env/dev branch

containerPort: 8888
service:
  port: 8888

env:
  EUREKA_URL: http://eureka-server:8761/eureka/
