image:
  repository: ghcr.io/13nour11/payment-service
  tag: latest

containerPort: 8083
service:
  port: 8083

env:
  CONFIG_SERVER_URL: http://config-server:8888
  EUREKA_URL: http://eureka-server:8761/eureka/
  POSTGRES_HOST: postgres.infra
  KAFKA_BOOTSTRAP_SERVERS: kafka.infra:9092
  # Must equal the iss claim, i.e. Keycloak KC_HOSTNAME in the cluster (infra manifest)
  KEYCLOAK_ISSUER_URI: http://localhost:8180/realms/ecommerce-platform
  KEYCLOAK_JWK_SET_URI: http://keycloak.infra:8180/realms/ecommerce-platform/protocol/openid-connect/certs

# Keys: see scripts/create-k8s-secrets.sh
secretName: payment-service-secrets
